### ISSUE TITLE
zsh compinit: insecure directories

### ISSUE THREAD

**Issue by michaelachrisco** [Shift3/laptop#11]
I got the following warning on a new Macbook Pro 2019: 
Mac OS Version: 10.15.4

New setup without any customization. 

```
Last login: Tue Apr  7 09:29:14 on ttys000
zsh compinit: insecure directories, run compaudit for list.
Ignore insecure directories and continue [y] or abort compinit [n]? y
zsh compinit: insecure directories, run compaudit for list.
Ignore insecure directories and continue [y] or abort compinit [n]? compinit: initialization aborted
complete:13: command not found: compdef
~ # compaudit
There are insecure directories:
/usr/local/share/zsh/site-functions
/usr/local/share/zsh
```

**Comment by michaelachrisco** [comment]
Fixed by doing the following:
https://github.com/zsh-users/zsh-completions/issues/433#issuecomment-600582607

Wondering if anyone else has had the same experience. If so, then the docs (or script) might need to be updated.

**Comment by DropsOfSerenity** [comment]
Thanks for this! Weird that zsh permissions on mac os are not correct by default. This solution seems potentially cleaner.

```bash
compaudit | xargs chmod g-w
```

**Comment by michaelachrisco** [comment]
Wouldn't be opposed! Maybe the script should take a look at the permission levels and give a warning? Or somewhat automatically do the fix. Either way, it was a quick fix.

**Comment by DropsOfSerenity** [comment]
Yep, I'll probably test it out when I can to see if that fixes it. And if so I will include is in the `os/mac` install script.

**Comment by michaelachrisco** [comment]
Awesome thanks.
