### ISSUE TITLE
Add aws cli and eb cli to initial install.

### ISSUE THREAD

**Issue by DropsOfSerenity** [Shift3/laptop#13]
At Shift3 we use AWS frequently enough to where the `aws` and `eb` cli's should be installed by default.

**Comment by michaelachrisco** [comment]
Should this be optional? how heavy are these two libraries?

**Comment by DropsOfSerenity** [comment]
Since AWS is our primary deployment platform, personally I think these should be mandatory. Both are python cli tools basically, the install process for each varies. I believe on osx you can install both from brew.

**Comment by michaelachrisco** [comment]
After running through the boilerplate projects, I am inclined to agree.

**Comment by Karvel** [comment]
Not our two Azure projects!

(I agree.)

**Comment by michaelachrisco** [comment]
We added terraform but did not add `awscli` within the laptop script. This came up in a new terraform installation.https://formulae.brew.sh/formula/awscli
