### ISSUE TITLE
Add CircleCI CLI and Terraform CLI

### ISSUE THREAD

**Issue by Karvel** [Shift3/laptop#14]
## Desired Use Case

As we consolidate the tools we use in our repositories, it could be nice to have some of them configured here. 

## Actual/Current Behavior

Not yet implemented.

## Steps to Implement This Feature

  1. Integrate the CircleCI CLI.
  2. Integrate the Terraform CLI.

## Learning

https://circleci.com/docs/2.0/local-cli/#installation
https://www.terraform.io/downloads.html

**Comment by michaelachrisco** [comment]
This came up on a mentoring session/training session recently. I think using Brew/standard installs will help save time/sanity. 

Terraform now has a Formulae: https://formulae.brew.sh/formula/terraform
