### ISSUE TITLE
Bug: using diffopt+=vertical produces error when starting vim

### ISSUE THREAD

**Issue by djagellon** [Shift3/laptop#24]
Not sure if this is considered a bug on our end since the error occurs with certain versions of macOS.

Starting with Catalina, the `vertical` value generates an error when starting vim:

`E474: Invalid argument: diffopt+=vertical`

See: https://github.com/thoughtbot/dotfiles/issues/655#issuecomment-605019271

Potential fix is to update the affected section in `vimrc`:
 
```
if &diff
    set diffopt+=vertical
endif
```

**Comment by djagellon** [comment]
@Endtry Trying to make a for this repo but I don't think I have write access.

**Comment by DropsOfSerenity** [comment]
@djagellon If you can make a pull request for this I can get it merged in.

**Comment by djagellon** [comment]
Thanks @DropsOfSerenity I tried to, but I don't seem to have write access to the repo.

**Comment by DropsOfSerenity** [comment]
@djagellon You'll want to fork the repository, then make a pull request from your fork :)

**Comment by djagellon** [comment]
ah. Thank you, I thought pulling and creating a new branch would be enough.
