### ISSUE TITLE
tfswitch - thoughts?

### ISSUE THREAD

**Issue by michaelachrisco** [Shift3/laptop#35]
What do we think of https://tfswitch.warrensbox.com/? Ive been using it since May of last year and it works like nvm for terraform. We can match the exact version of terraform when doing debug sessions. Its also easier to maintain when needing specific version of terraform to deploy or get updated. 

Installation instructions are pretty easy: https://tfswitch.warrensbox.com/Install/ It also seems to be well maintained.

**Comment by DropsOfSerenity** [comment]
@michaelachrisco Interesting, I think we could make this work if we specify and sync up version in boilerplates and with devops.

@mwallert What do you think?

**Comment by kvendingoldo** [comment]
btw. you can also use [tenv](https://github.com/tofuutils/tenv) that support Terraform as well as OpenTofu (and Terragrunt :) ) in one tool. It allow you to simplify version management and can do much more, than tfswitch.
