### ISSUE TITLE
Long term maintanance of the repo

### ISSUE THREAD

**Issue by michaelachrisco** [Shift3/laptop#39]
@coreyshuman / @mwallert / Anyone 
Couple of questions that are related to this repo. 

What does long term maintenance look like for this repo? Justin spearheaded this repo (and did an amazing job at it) but now we dont have a dedicated dev/team looking at our common tools (at least that I am aware).  

Does the shop still use this in the on-boarding of new developers? 

Should DevOps own this repo or Architecture? Someone else?

I personally still think it still provides value. And I would still like to se tfswitch to be part of the repo as well as more testing within the Mac OS side (Circleci or otherwise). But I would like to hear peoples thoughts and get their feedback. I have a feeling most just set and forget about these tools once the are installed.

**Comment by kvendingoldo** [comment]
btw. you can also use [tenv](https://github.com/tofuutils/tenv) that support Terraform as well as OpenTofu (and Terragrunt :) ) in one tool. It allow you to simplify version management and can do much more, than tfswitch.
